import type { Metadata } from "next";
import "./globals.css";
import Hero from "./pages/hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-center text-black">
        {children}
        <Hero />
      </body>
    </html>
  );
}
